version: '3'
services: 
    web:
        build:   '.'
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules
        ports:
            - "80:3000"
        environment: 
            DB_HOST: postgres
            DB_USER: pguser
            DB_PORT: 5432
            DB_PASSWORD: pgpassword
            DB_DB: pgdb
        links: 
            - postgres
        depends_on: 
            - postgres
            
    postgres:
        image: postgres:11.2-alpine
        restart: always
        hostname: postgres
        ports: 
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: pgpassword
            POSTGRES_USER: pguser
            POSTGRES_DB:   pgdb